# Generated by Django 4.1 on 2022-08-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year_publications',
            name='publication_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='year_publications',
            name='year',
            field=models.IntegerField(),
        ),
    ]
