# Generated by Django 4.1 on 2022-08-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_alter_year_publications_publication_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=1500)),
                ('scopus_url', models.URLField(blank=True, max_length=500, null=True)),
                ('DOI', models.CharField(max_length=100)),
                ('affiliation', models.TextField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('ISSN', models.CharField(blank=True, max_length=20, null=True)),
                ('document_type', models.CharField(choices=[('Conference Paper', 'Conference Paper'), ('Article', 'Article'), ('Book Chapter', 'Book Chapter'), ('Book', 'Book'), ('Editorial', 'Editorial'), ('Review', 'Review'), ('Letter', 'Letter')], max_length=50)),
                ('publication_stage', models.CharField(blank=True, max_length=50, null=True)),
                ('open_access', models.CharField(blank=True, max_length=50, null=True)),
                ('publishing_year', models.IntegerField()),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('cited_by', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='year_publications',
            options={'verbose_name_plural': 'Year Publications'},
        ),
    ]
