# Generated by Django 4.1 on 2022-08-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publication_alter_year_publications_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='cited_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
