# Generated by Django 4.1 on 2022-08-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_alter_publication_cited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='DOI',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
