# Generated by Django 4.1 on 2022-08-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_alter_publication_doi'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='ISBN',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='ISSN',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
